# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /thayerfs/home/f0056cj/workspace/Module5/Module5.srcs/sources_1/bd/Module5_hw/ip/Module5_hw_axi_gpio_1_0/Module5_hw_axi_gpio_1_0.xci
# IP: The module: 'Module5_hw_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /thayerfs/home/f0056cj/workspace/Module5/Module5.gen/sources_1/bd/Module5_hw/ip/Module5_hw_axi_gpio_1_0/Module5_hw_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Module5_hw_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /thayerfs/home/f0056cj/workspace/Module5/Module5.gen/sources_1/bd/Module5_hw/ip/Module5_hw_axi_gpio_1_0/Module5_hw_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Module5_hw_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /thayerfs/home/f0056cj/workspace/Module5/Module5.gen/sources_1/bd/Module5_hw/ip/Module5_hw_axi_gpio_1_0/Module5_hw_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Module5_hw_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /thayerfs/home/f0056cj/workspace/Module5/Module5.srcs/sources_1/bd/Module5_hw/ip/Module5_hw_axi_gpio_1_0/Module5_hw_axi_gpio_1_0.xci
# IP: The module: 'Module5_hw_axi_gpio_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /thayerfs/home/f0056cj/workspace/Module5/Module5.gen/sources_1/bd/Module5_hw/ip/Module5_hw_axi_gpio_1_0/Module5_hw_axi_gpio_1_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Module5_hw_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /thayerfs/home/f0056cj/workspace/Module5/Module5.gen/sources_1/bd/Module5_hw/ip/Module5_hw_axi_gpio_1_0/Module5_hw_axi_gpio_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Module5_hw_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /thayerfs/home/f0056cj/workspace/Module5/Module5.gen/sources_1/bd/Module5_hw/ip/Module5_hw_axi_gpio_1_0/Module5_hw_axi_gpio_1_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Module5_hw_axi_gpio_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
