# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /thayerfs/home/f0056cj/srcs/Zybo-Z7-Master.xdc

# Block Designs: bd/Module5_hw/Module5_hw.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Module5_hw || ORIG_REF_NAME==Module5_hw} -quiet] -quiet

# IP: bd/Module5_hw/ip/Module5_hw_processing_system7_0_0/Module5_hw_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Module5_hw_processing_system7_0_0 || ORIG_REF_NAME==Module5_hw_processing_system7_0_0} -quiet] -quiet

# IP: bd/Module5_hw/ip/Module5_hw_axi_gpio_0_0/Module5_hw_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Module5_hw_axi_gpio_0_0 || ORIG_REF_NAME==Module5_hw_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Module5_hw/ip/Module5_hw_xbar_0/Module5_hw_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Module5_hw_xbar_0 || ORIG_REF_NAME==Module5_hw_xbar_0} -quiet] -quiet

# IP: bd/Module5_hw/ip/Module5_hw_ps7_0_axi_periph_0/Module5_hw_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Module5_hw_ps7_0_axi_periph_0 || ORIG_REF_NAME==Module5_hw_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/Module5_hw/ip/Module5_hw_rst_ps7_0_50M_0/Module5_hw_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Module5_hw_rst_ps7_0_50M_0 || ORIG_REF_NAME==Module5_hw_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/Module5_hw/ip/Module5_hw_axi_gpio_1_0/Module5_hw_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Module5_hw_axi_gpio_1_0 || ORIG_REF_NAME==Module5_hw_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Module5_hw/ip/Module5_hw_axi_gpio_2_0/Module5_hw_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Module5_hw_axi_gpio_2_0 || ORIG_REF_NAME==Module5_hw_axi_gpio_2_0} -quiet] -quiet

# IP: bd/Module5_hw/ip/Module5_hw_xlconcat_0_0/Module5_hw_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Module5_hw_xlconcat_0_0 || ORIG_REF_NAME==Module5_hw_xlconcat_0_0} -quiet] -quiet

# IP: bd/Module5_hw/ip/Module5_hw_auto_pc_0/Module5_hw_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Module5_hw_auto_pc_0 || ORIG_REF_NAME==Module5_hw_auto_pc_0} -quiet] -quiet

# XDC: /thayerfs/home/f0056cj/workspace/Module5/Module5.gen/sources_1/bd/Module5_hw/Module5_hw_ooc.xdc
